#!bin/bash
mkdir "1.loops"
mkdir "2.loops-practice"
mkdir "3.loops-practice"
mkdir "4.loop-review"
mkdir "5.loop-review"
mkdir "6.whitespace-in-python"
mkdir "7.range-continued"
mkdir "8.sum-game"
mkdir "9.sum-game-2"
mkdir "10.while"
mkdir "11.match-countdown"
mkdir "12.experience-points"
mkdir "13.meditate"
