#!bin/bash
mkdir "1.comparison-operators"
mkdir "2.comparison-operator-evaluations"
mkdir "3.comparison-practice"
mkdir "4.if-statements"
mkdir "5.if-practice"
mkdir "6.if-else"
mkdir "7.if-else-practice"
mkdir "8.if-else-practice"
mkdir "9.boolean-logic"
mkdir "10.boolean-quiz"
mkdir "11.should-serve-drinks"
mkdir "12.mount-rental"
mkdir "13.combat-advantage"
