#!/usr/bin/env python

def main():
    curr = 1
    for i in range(10_000_000):
        for j in range(10_000):
            # Looking busy huh
            pass
        if i == curr * 10:
            curr = i
            print(i)


if __name__ == "__main__":
    main()
